server:
  port: ${APP_SERVER_PORT:8080}

spring:
  application:
    name: kafka-event-sourcing
  datasource:
    url: jdbc:postgresql://${APP_DB_HOST:192.168.19.64}:${APP_DB_PORT:5432}/${APP_DB_NAME:kafka-learn}
    username: ${APP_DB_USERNAME:postgres}
    password: ${APP_DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: ${APP_KAFKA_BOOTSTRAP_SERVERS:192.168.19.64:9092}
    producer:
      acks: all
      retries: 3
      batch-size: 16384
      linger-ms: 10
      compression-type: snappy
      request-timeout-ms: 30000
    consumer:
      group-id: ${APP_KAFKA_CONSUMER_GROUP:account-projection-group}
      auto-offset-reset: earliest
      enable-auto-commit: true
      max-poll-records: 500

logging:
  file:
    path: ${LOGGIN_FILE_PATH:./Kafka-EventSourcing/log}

